.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container\-wait \- Block until one or more containers stop, then print their exit codes


.SH SYNOPSIS
.PP
\fBdocker container wait CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Block until a container stops, then print its exit code.


.SH EXAMPLES
.PP
.RS

.nf
$ docker run \-d fedora sleep 99
079b83f558a2bc52ecad6b2a5de13622d584e6bb1aea058c11b36511e85e7622
$ docker container wait 079b83f558a2bc
0

.fi
.RE


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for wait


.SH SEE ALSO
.PP
\fBdocker\-container(1)\fP
