.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-service \- Manage services


.SH SYNOPSIS
.PP
\fBdocker service\fP


.SH DESCRIPTION
.PP
Manage services


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for service


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-service\-create(1)\fP, \fBdocker\-service\-inspect(1)\fP, \fBdocker\-service\-logs(1)\fP, \fBdocker\-service\-ls(1)\fP, \fBdocker\-service\-ps(1)\fP, \fBdocker\-service\-rm(1)\fP, \fBdocker\-service\-rollback(1)\fP, \fBdocker\-service\-scale(1)\fP, \fBdocker\-service\-update(1)\fP
