.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-manifest\-create \- Create a local manifest list for annotating and pushing to a registry


.SH SYNOPSIS
.PP
\fBdocker manifest create MANIFEST\_LIST MANIFEST [MANIFEST...]\fP


.SH DESCRIPTION
.PP
Create a local manifest list for annotating and pushing to a registry


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-amend\fP[=false]
    Amend an existing manifest list

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for create

.PP
\fB\-\-insecure\fP[=false]
    Allow communication with an insecure registry


.SH SEE ALSO
.PP
\fBdocker\-manifest(1)\fP
