.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container\-diff \- Inspect changes to files or directories on a container's filesystem


.SH SYNOPSIS
.PP
\fBdocker container diff CONTAINER\fP


.SH DESCRIPTION
.PP
List the changed files and directories in a container᾿s filesystem since the
container was created. Three different types of change are tracked:

.TS
allbox;
l l 
l l .
\fB\fCSymbol\fR	\fB\fCDescription\fR
\fB\fCA\fR	A file or directory was added
\fB\fCD\fR	T{
A file or directory was deleted
T}
\fB\fCC\fR	T{
A file or directory was changed
T}
.TE

.PP
You can use the full or shortened container ID or the container name set using
\fBdocker run \-\-name\fP option.


.SH EXAMPLES
.PP
Inspect the changes to an \fB\fCnginx\fR container:

.PP
.RS

.nf
$ docker diff 1fdfd1f54c1b

C /dev
C /dev/console
C /dev/core
C /dev/stdout
C /dev/fd
C /dev/ptmx
C /dev/stderr
C /dev/stdin
C /run
A /run/nginx.pid
C /var/lib/nginx/tmp
A /var/lib/nginx/tmp/client\_body
A /var/lib/nginx/tmp/fastcgi
A /var/lib/nginx/tmp/proxy
A /var/lib/nginx/tmp/scgi
A /var/lib/nginx/tmp/uwsgi
C /var/log/nginx
A /var/log/nginx/access.log
A /var/log/nginx/error.log

.fi
.RE


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for diff


.SH SEE ALSO
.PP
\fBdocker\-container(1)\fP
