.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-logs \- Fetch the logs of a container


.SH SYNOPSIS
.PP
\fBdocker logs [OPTIONS] CONTAINER\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container logs\fR\&.


.SH OPTIONS
.PP
\fB\-\-details\fP[=false]
    Show extra details provided to logs

.PP
\fB\-f\fP, \fB\-\-follow\fP[=false]
    Follow log output

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for logs

.PP
\fB\-\-since\fP=""
    Show logs since timestamp (e.g. 2013\-01\-02T13:23:37) or relative (e.g. 42m for 42 minutes)

.PP
\fB\-\-tail\fP="all"
    Number of lines to show from the end of the logs

.PP
\fB\-t\fP, \fB\-\-timestamps\fP[=false]
    Show timestamps

.PP
\fB\-\-until\fP=""
    Show logs before a timestamp (e.g. 2013\-01\-02T13:23:37) or relative (e.g. 42m for 42 minutes)


.SH SEE ALSO
.PP
\fBdocker(1)\fP
