.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-update \- Update configuration of one or more containers


.SH SYNOPSIS
.PP
\fBdocker update [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container update\fR\&.


.SH OPTIONS
.PP
\fB\-\-blkio\-weight\fP=0
    Block IO (relative weight), between 10 and 1000, or 0 to disable (default 0)

.PP
\fB\-\-cpu\-period\fP=0
    Limit CPU CFS (Completely Fair Scheduler) period

.PP
\fB\-\-cpu\-quota\fP=0
    Limit CPU CFS (Completely Fair Scheduler) quota

.PP
\fB\-\-cpu\-rt\-period\fP=0
    Limit the CPU real\-time period in microseconds

.PP
\fB\-\-cpu\-rt\-runtime\fP=0
    Limit the CPU real\-time runtime in microseconds

.PP
\fB\-c\fP, \fB\-\-cpu\-shares\fP=0
    CPU shares (relative weight)

.PP
\fB\-\-cpus\fP=
    Number of CPUs

.PP
\fB\-\-cpuset\-cpus\fP=""
    CPUs in which to allow execution (0\-3, 0,1)

.PP
\fB\-\-cpuset\-mems\fP=""
    MEMs in which to allow execution (0\-3, 0,1)

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for update

.PP
\fB\-\-kernel\-memory\fP=0
    Kernel memory limit

.PP
\fB\-m\fP, \fB\-\-memory\fP=0
    Memory limit

.PP
\fB\-\-memory\-reservation\fP=0
    Memory soft limit

.PP
\fB\-\-memory\-swap\fP=0
    Swap limit equal to memory plus swap: '\-1' to enable unlimited swap

.PP
\fB\-\-pids\-limit\fP=0
    Tune container pids limit (set \-1 for unlimited)

.PP
\fB\-\-restart\fP=""
    Restart policy to apply when a container exits


.SH SEE ALSO
.PP
\fBdocker(1)\fP
