.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-service\-logs \- Fetch the logs of a service or task


.SH SYNOPSIS
.PP
\fBdocker service logs [OPTIONS] SERVICE|TASK\fP


.SH DESCRIPTION
.PP
Fetch the logs of a service or task


.SH OPTIONS
.PP
\fB\-\-details\fP[=false]
    Show extra details provided to logs

.PP
\fB\-f\fP, \fB\-\-follow\fP[=false]
    Follow log output

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for logs

.PP
\fB\-\-no\-resolve\fP[=false]
    Do not map IDs to Names in output

.PP
\fB\-\-no\-task\-ids\fP[=false]
    Do not include task IDs in output

.PP
\fB\-\-no\-trunc\fP[=false]
    Do not truncate output

.PP
\fB\-\-raw\fP[=false]
    Do not neatly format logs

.PP
\fB\-\-since\fP=""
    Show logs since timestamp (e.g. 2013\-01\-02T13:23:37) or relative (e.g. 42m for 42 minutes)

.PP
\fB\-\-tail\fP="all"
    Number of lines to show from the end of the logs

.PP
\fB\-t\fP, \fB\-\-timestamps\fP[=false]
    Show timestamps


.SH SEE ALSO
.PP
\fBdocker\-service(1)\fP
