.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-wait \- Block until one or more containers stop, then print their exit codes


.SH SYNOPSIS
.PP
\fBdocker wait CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container wait\fR\&.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for wait


.SH SEE ALSO
.PP
\fBdocker(1)\fP
