.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-image\-prune \- Remove unused images


.SH SYNOPSIS
.PP
\fBdocker image prune [OPTIONS]\fP


.SH DESCRIPTION
.PP
Remove unused images


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
    Remove all unused images, not just dangling ones

.PP
\fB\-\-filter\fP=
    Provide filter values (e.g. 'until=<timestamp>\&')

.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Do not prompt for confirmation

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for prune


.SH SEE ALSO
.PP
\fBdocker\-image(1)\fP
