.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container\-pause \- Pause all processes within one or more containers


.SH SYNOPSIS
.PP
\fBdocker container pause CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
The \fB\fCdocker container pause\fR command suspends all processes in the specified containers.
On Linux, this uses the cgroups freezer. Traditionally, when suspending a process
the \fB\fCSIGSTOP\fR signal is used, which is observable by the process being suspended.
With the cgroups freezer the process is unaware, and unable to capture,
that it is being suspended, and subsequently resumed. On Windows, only Hyper\-V
containers can be paused.

.PP
See the cgroups freezer documentation
\[la]https://www.kernel.org/doc/Documentation/cgroup-v1/freezer-subsystem.txt\[ra] for
further details.

.PP
\fBdocker\-container\-unpause(1)\fP to unpause all processes within a container.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for pause


.SH SEE ALSO
.PP
\fBdocker\-container(1)\fP
