.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-import \- Import the contents from a tarball to create a filesystem image


.SH SYNOPSIS
.PP
\fBdocker import [OPTIONS] file|URL|\- [REPOSITORY[:TAG]]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker image import\fR\&.


.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-change\fP=
    Apply Dockerfile instruction to the created image

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for import

.PP
\fB\-m\fP, \fB\-\-message\fP=""
    Set commit message for imported image


.SH SEE ALSO
.PP
\fBdocker(1)\fP
