.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container\-restart \- Restart one or more containers


.SH SYNOPSIS
.PP
\fBdocker container restart [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Restart each container listed.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for restart

.PP
\fB\-t\fP, \fB\-\-time\fP=10
    Seconds to wait for stop before killing the container


.SH SEE ALSO
.PP
\fBdocker\-container(1)\fP
