.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-trust\-sign \- Sign an image


.SH SYNOPSIS
.PP
\fBdocker trust sign IMAGE:TAG\fP


.SH DESCRIPTION
.PP
Sign an image


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for sign

.PP
\fB\-\-local\fP[=false]
    Sign a locally tagged image


.SH SEE ALSO
.PP
\fBdocker\-trust(1)\fP
