.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container\-inspect \- Display detailed information on one or more containers


.SH SYNOPSIS
.PP
\fBdocker container inspect [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Display detailed information on one or more containers


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-format\fP=""
    Format the output using the given Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for inspect

.PP
\fB\-s\fP, \fB\-\-size\fP[=false]
    Display total file sizes


.SH SEE ALSO
.PP
\fBdocker\-container(1)\fP
