.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-load \- Load an image from a tar archive or STDIN


.SH SYNOPSIS
.PP
\fBdocker load [OPTIONS]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker image load\fR\&.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for load

.PP
\fB\-i\fP, \fB\-\-input\fP=""
    Read from tar archive file, instead of STDIN

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Suppress the load output


.SH SEE ALSO
.PP
\fBdocker(1)\fP
