.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-stop \- Stop one or more running containers


.SH SYNOPSIS
.PP
\fBdocker stop [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container stop\fR\&.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for stop

.PP
\fB\-t\fP, \fB\-\-time\fP=10
    Seconds to wait for stop before killing it


.SH SEE ALSO
.PP
\fBdocker(1)\fP
