.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-swarm\-leave \- Leave the swarm


.SH SYNOPSIS
.PP
\fBdocker swarm leave [OPTIONS]\fP


.SH DESCRIPTION
.PP
Leave the swarm


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Force this node to leave the swarm, ignoring warnings

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for leave


.SH SEE ALSO
.PP
\fBdocker\-swarm(1)\fP
