.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-info \- Display system\-wide information


.SH SYNOPSIS
.PP
\fBdocker info [OPTIONS]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker system info\fR\&.


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-format\fP=""
    Format the output using the given Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for info


.SH SEE ALSO
.PP
\fBdocker(1)\fP
