.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-plugin\-enable \- Enable a plugin


.SH SYNOPSIS
.PP
\fBdocker plugin enable [OPTIONS] PLUGIN\fP


.SH DESCRIPTION
.PP
Enable a plugin


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for enable

.PP
\fB\-\-timeout\fP=30
    HTTP client timeout (in seconds)


.SH SEE ALSO
.PP
\fBdocker\-plugin(1)\fP
