.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-secret\-create \- Create a secret from a file or STDIN as content


.SH SYNOPSIS
.PP
\fBdocker secret create [OPTIONS] SECRET [file|\-]\fP


.SH DESCRIPTION
.PP
Create a secret from a file or STDIN as content


.SH OPTIONS
.PP
\fB\-d\fP, \fB\-\-driver\fP=""
    Secret driver

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for create

.PP
\fB\-l\fP, \fB\-\-label\fP=
    Secret labels

.PP
\fB\-\-template\-driver\fP=""
    Template driver


.SH SEE ALSO
.PP
\fBdocker\-secret(1)\fP
