.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container\-rename \- Rename a container


.SH SYNOPSIS
.PP
\fBdocker container rename CONTAINER NEW\_NAME\fP


.SH DESCRIPTION
.PP
Rename a container.  Container may be running, paused or stopped.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for rename


.SH SEE ALSO
.PP
\fBdocker\-container(1)\fP
