.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-push \- Push an image or a repository to a registry


.SH SYNOPSIS
.PP
\fBdocker push [OPTIONS] NAME[:TAG]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker image push\fR\&.


.SH OPTIONS
.PP
\fB\-\-disable\-content\-trust\fP[=true]
    Skip image signing

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for push


.SH SEE ALSO
.PP
\fBdocker(1)\fP
