.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-context\-ls \- List contexts


.SH SYNOPSIS
.PP
\fBdocker context ls [OPTIONS]\fP


.SH DESCRIPTION
.PP
List contexts


.SH OPTIONS
.PP
\fB\-\-format\fP=""
    Pretty\-print contexts using a Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for ls

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only show context names


.SH SEE ALSO
.PP
\fBdocker\-context(1)\fP
