.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-manifest\-push \- Push a manifest list to a repository


.SH SYNOPSIS
.PP
\fBdocker manifest push [OPTIONS] MANIFEST\_LIST\fP


.SH DESCRIPTION
.PP
Push a manifest list to a repository


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for push

.PP
\fB\-\-insecure\fP[=false]
    Allow push to an insecure registry

.PP
\fB\-p\fP, \fB\-\-purge\fP[=false]
    Remove the local manifest list after push


.SH SEE ALSO
.PP
\fBdocker\-manifest(1)\fP
