.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-pull \- Pull an image or a repository from a registry


.SH SYNOPSIS
.PP
\fBdocker pull [OPTIONS] NAME[:TAG|@DIGEST]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker image pull\fR\&.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\-tags\fP[=false]
    Download all tagged images in the repository

.PP
\fB\-\-disable\-content\-trust\fP[=true]
    Skip image verification

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for pull

.PP
\fB\-\-platform\fP=""
    Set platform if server is multi\-platform capable


.SH SEE ALSO
.PP
\fBdocker(1)\fP
