.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-stats \- Display a live stream of container(s) resource usage statistics


.SH SYNOPSIS
.PP
\fBdocker stats [OPTIONS] [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container stats\fR\&.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
    Show all containers (default shows just running)

.PP
\fB\-\-format\fP=""
    Pretty\-print images using a Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for stats

.PP
\fB\-\-no\-stream\fP[=false]
    Disable streaming stats and only pull the first result

.PP
\fB\-\-no\-trunc\fP[=false]
    Do not truncate output


.SH SEE ALSO
.PP
\fBdocker(1)\fP
