.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-image\-rm \- Remove one or more images


.SH SYNOPSIS
.PP
\fBdocker image rm [OPTIONS] IMAGE [IMAGE...]\fP


.SH DESCRIPTION
.PP
Removes one or more images from the host node. This does not remove images from
a registry. You cannot remove an image of a running container unless you use the
\fB\-f\fP option. To see all images on a host use the \fBdocker image ls\fP command.


.SH EXAMPLES
.SH Removing an image
.PP
Here is an example of removing an image:

.PP
.RS

.nf
docker image rm fedora/httpd

.fi
.RE


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Force removal of the image

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for rm

.PP
\fB\-\-no\-prune\fP[=false]
    Do not delete untagged parents


.SH SEE ALSO
.PP
\fBdocker\-image(1)\fP
