.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-service\-rollback \- Revert changes to a service's configuration


.SH SYNOPSIS
.PP
\fBdocker service rollback [OPTIONS] SERVICE\fP


.SH DESCRIPTION
.PP
Revert changes to a service's configuration


.SH OPTIONS
.PP
\fB\-d\fP, \fB\-\-detach\fP[=false]
    Exit immediately instead of waiting for the service to converge

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for rollback

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Suppress progress output


.SH SEE ALSO
.PP
\fBdocker\-service(1)\fP
