.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-volume\-prune \- Remove all unused local volumes


.SH SYNOPSIS
.PP
\fBdocker volume prune [OPTIONS]\fP


.SH DESCRIPTION
.PP
Remove all unused local volumes


.SH OPTIONS
.PP
\fB\-\-filter\fP=
    Provide filter values (e.g. 'label=<label>\&')

.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Do not prompt for confirmation

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for prune


.SH SEE ALSO
.PP
\fBdocker\-volume(1)\fP
