.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-plugin\-rm \- Remove one or more plugins


.SH SYNOPSIS
.PP
\fBdocker plugin rm [OPTIONS] PLUGIN [PLUGIN...]\fP


.SH DESCRIPTION
.PP
Remove one or more plugins


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Force the removal of an active plugin

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for rm


.SH SEE ALSO
.PP
\fBdocker\-plugin(1)\fP
