.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-engine\-update \- Update a local engine


.SH SYNOPSIS
.PP
\fBdocker engine update [OPTIONS]\fP


.SH DESCRIPTION
.PP
Update a local engine


.SH OPTIONS
.PP
\fB\-\-containerd\fP=""
    override default location of containerd endpoint

.PP
\fB\-\-engine\-image\fP=""
    Specify engine image (default uses the same image as currently running)

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for update

.PP
\fB\-\-registry\-prefix\fP="docker.io/store/docker"
    Override the current location where engine images are pulled

.PP
\fB\-\-version\fP=""
    Specify engine version


.SH SEE ALSO
.PP
\fBdocker\-engine(1)\fP
