.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container \- Manage containers


.SH SYNOPSIS
.PP
\fBdocker container\fP


.SH DESCRIPTION
.PP
Manage containers


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for container


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-container\-attach(1)\fP, \fBdocker\-container\-commit(1)\fP, \fBdocker\-container\-cp(1)\fP, \fBdocker\-container\-create(1)\fP, \fBdocker\-container\-diff(1)\fP, \fBdocker\-container\-exec(1)\fP, \fBdocker\-container\-export(1)\fP, \fBdocker\-container\-inspect(1)\fP, \fBdocker\-container\-kill(1)\fP, \fBdocker\-container\-logs(1)\fP, \fBdocker\-container\-ls(1)\fP, \fBdocker\-container\-pause(1)\fP, \fBdocker\-container\-port(1)\fP, \fBdocker\-container\-prune(1)\fP, \fBdocker\-container\-rename(1)\fP, \fBdocker\-container\-restart(1)\fP, \fBdocker\-container\-rm(1)\fP, \fBdocker\-container\-run(1)\fP, \fBdocker\-container\-start(1)\fP, \fBdocker\-container\-stats(1)\fP, \fBdocker\-container\-stop(1)\fP, \fBdocker\-container\-top(1)\fP, \fBdocker\-container\-unpause(1)\fP, \fBdocker\-container\-update(1)\fP, \fBdocker\-container\-wait(1)\fP
