.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-images \- List images


.SH SYNOPSIS
.PP
\fBdocker images [OPTIONS] [REPOSITORY[:TAG]]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker image ls\fR\&.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
    Show all images (default hides intermediate images)

.PP
\fB\-\-digests\fP[=false]
    Show digests

.PP
\fB\-f\fP, \fB\-\-filter\fP=
    Filter output based on conditions provided

.PP
\fB\-\-format\fP=""
    Pretty\-print images using a Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for images

.PP
\fB\-\-no\-trunc\fP[=false]
    Don't truncate output

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only show numeric IDs


.SH SEE ALSO
.PP
\fBdocker(1)\fP
