.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-plugin\-upgrade \- Upgrade an existing plugin


.SH SYNOPSIS
.PP
\fBdocker plugin upgrade [OPTIONS] PLUGIN [REMOTE]\fP


.SH DESCRIPTION
.PP
Upgrade an existing plugin


.SH OPTIONS
.PP
\fB\-\-disable\-content\-trust\fP[=true]
    Skip image verification

.PP
\fB\-\-grant\-all\-permissions\fP[=false]
    Grant all permissions necessary to run the plugin

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for upgrade

.PP
\fB\-\-skip\-remote\-check\fP[=false]
    Do not check if specified remote plugin matches existing plugin image


.SH SEE ALSO
.PP
\fBdocker\-plugin(1)\fP
