.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-service\-scale \- Scale one or multiple replicated services


.SH SYNOPSIS
.PP
\fBdocker service scale SERVICE=REPLICAS [SERVICE=REPLICAS...]\fP


.SH DESCRIPTION
.PP
Scale one or multiple replicated services


.SH OPTIONS
.PP
\fB\-d\fP, \fB\-\-detach\fP[=false]
    Exit immediately instead of waiting for the service to converge

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for scale


.SH SEE ALSO
.PP
\fBdocker\-service(1)\fP
