.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-pause \- Pause all processes within one or more containers


.SH SYNOPSIS
.PP
\fBdocker pause CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container pause\fR\&.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for pause


.SH SEE ALSO
.PP
\fBdocker(1)\fP
