.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-swarm\-unlock\-key \- Manage the unlock key


.SH SYNOPSIS
.PP
\fBdocker swarm unlock\-key [OPTIONS]\fP


.SH DESCRIPTION
.PP
Manage the unlock key


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for unlock\-key

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only display token

.PP
\fB\-\-rotate\fP[=false]
    Rotate unlock key


.SH SEE ALSO
.PP
\fBdocker\-swarm(1)\fP
