.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-swarm\-ca \- Display and rotate the root CA


.SH SYNOPSIS
.PP
\fBdocker swarm ca [OPTIONS]\fP


.SH DESCRIPTION
.PP
Display and rotate the root CA


.SH OPTIONS
.PP
\fB\-\-ca\-cert\fP=
    Path to the PEM\-formatted root CA certificate to use for the new cluster

.PP
\fB\-\-ca\-key\fP=
    Path to the PEM\-formatted root CA key to use for the new cluster

.PP
\fB\-\-cert\-expiry\fP=2160h0m0s
    Validity period for node certificates (ns|us|ms|s|m|h)

.PP
\fB\-d\fP, \fB\-\-detach\fP[=false]
    Exit immediately instead of waiting for the root rotation to converge

.PP
\fB\-\-external\-ca\fP=
    Specifications of one or more certificate signing endpoints

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for ca

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Suppress progress output

.PP
\fB\-\-rotate\fP[=false]
    Rotate the swarm CA \- if no certificate or key are provided, new ones will be generated


.SH SEE ALSO
.PP
\fBdocker\-swarm(1)\fP
