.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-trust\-signer\-remove \- Remove a signer


.SH SYNOPSIS
.PP
\fBdocker trust signer remove [OPTIONS] NAME REPOSITORY [REPOSITORY...]\fP


.SH DESCRIPTION
.PP
Remove a signer


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Do not prompt for confirmation before removing the most recent signer

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for remove


.SH SEE ALSO
.PP
\fBdocker\-trust\-signer(1)\fP
