.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-engine\-check \- Check for available engine updates


.SH SYNOPSIS
.PP
\fBdocker engine check [OPTIONS]\fP


.SH DESCRIPTION
.PP
Check for available engine updates


.SH OPTIONS
.PP
\fB\-\-containerd\fP=""
    override default location of containerd endpoint

.PP
\fB\-\-downgrades\fP[=false]
    Report downgrades (default omits older versions)

.PP
\fB\-\-engine\-image\fP=""
    Specify engine image (default uses the same image as currently running)

.PP
\fB\-\-format\fP=""
    Pretty\-print updates using a Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for check

.PP
\fB\-\-pre\-releases\fP[=false]
    Include pre\-release versions

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only display available versions

.PP
\fB\-\-registry\-prefix\fP="docker.io/store/docker"
    Override the existing location where engine images are pulled

.PP
\fB\-\-upgrades\fP[=true]
    Report available upgrades


.SH SEE ALSO
.PP
\fBdocker\-engine(1)\fP
