.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-start \- Start one or more stopped containers


.SH SYNOPSIS
.PP
\fBdocker start [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container start\fR\&.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-attach\fP[=false]
    Attach STDOUT/STDERR and forward signals

.PP
\fB\-\-checkpoint\fP=""
    Restore from this checkpoint

.PP
\fB\-\-checkpoint\-dir\fP=""
    Use a custom checkpoint storage directory

.PP
\fB\-\-detach\-keys\fP=""
    Override the key sequence for detaching a container

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for start

.PP
\fB\-i\fP, \fB\-\-interactive\fP[=false]
    Attach container's STDIN


.SH SEE ALSO
.PP
\fBdocker(1)\fP
