.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-service\-ls \- List services


.SH SYNOPSIS
.PP
\fBdocker service ls [OPTIONS]\fP


.SH DESCRIPTION
.PP
List services


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filter\fP=
    Filter output based on conditions provided

.PP
\fB\-\-format\fP=""
    Pretty\-print services using a Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for ls

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only display IDs


.SH SEE ALSO
.PP
\fBdocker\-service(1)\fP
