.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-trust\-signer \- Manage entities who can sign Docker images


.SH SYNOPSIS
.PP
\fBdocker trust signer\fP


.SH DESCRIPTION
.PP
Manage entities who can sign Docker images


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for signer


.SH SEE ALSO
.PP
\fBdocker\-trust(1)\fP, \fBdocker\-trust\-signer\-add(1)\fP, \fBdocker\-trust\-signer\-remove(1)\fP
