.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-trust\-key\-load \- Load a private key file for signing


.SH SYNOPSIS
.PP
\fBdocker trust key load [OPTIONS] KEYFILE\fP


.SH DESCRIPTION
.PP
Load a private key file for signing


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for load

.PP
\fB\-\-name\fP="signer"
    Name for the loaded key


.SH SEE ALSO
.PP
\fBdocker\-trust\-key(1)\fP
