.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-engine\-activate \- Activate Enterprise Edition


.SH SYNOPSIS
.PP
\fBdocker engine activate [OPTIONS]\fP


.SH DESCRIPTION
.PP
Activate Enterprise Edition.

.PP
With this command you may apply an existing Docker enterprise license, or
interactively download one from Docker. In the interactive exchange, you can
sign up for a new trial, or download an existing license. If you are
currently running a Community Edition engine, the daemon will be updated to
the Enterprise Edition Docker engine with additional capabilities and long
term support.

.PP
For more information about different Docker Enterprise license types visit

\[la]https://www.docker.com/licenses\[ra]

.PP
For non\-interactive scriptable deployments, download your license from

\[la]https://hub.docker.com/\[ra] then specify the file with the '\-\-license' flag.


.SH OPTIONS
.PP
\fB\-\-containerd\fP=""
    override default location of containerd endpoint

.PP
\fB\-\-display\-only\fP[=false]
    only display license information and exit

.PP
\fB\-\-engine\-image\fP=""
    Specify engine image

.PP
\fB\-\-format\fP=""
    Pretty\-print licenses using a Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for activate

.PP
\fB\-\-license\fP=""
    License File

.PP
\fB\-\-quiet\fP[=false]
    Only display available licenses by ID

.PP
\fB\-\-registry\-prefix\fP="docker.io/store/docker"
    Override the default location where engine images are pulled

.PP
\fB\-\-version\fP=""
    Specify engine version (default is to use currently running version)


.SH SEE ALSO
.PP
\fBdocker\-engine(1)\fP
