.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container\-port \- List port mappings or a specific mapping for the container


.SH SYNOPSIS
.PP
\fBdocker container port CONTAINER [PRIVATE\_PORT[/PROTO]]\fP


.SH DESCRIPTION
.PP
List port mappings for the CONTAINER, or lookup the public\-facing port that is NAT\-ed to the PRIVATE\_PORT


.SH EXAMPLES
.PP
.RS

.nf
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                            NAMES
b650456536c7        busybox:latest      top                 54 minutes ago      Up 54 minutes       0.0.0.0:1234\->9876/tcp, 0.0.0.0:4321\->7890/tcp   test

.fi
.RE

.SH Find out all the ports mapped
.PP
.RS

.nf
$ docker container port test
7890/tcp \-> 0.0.0.0:4321
9876/tcp \-> 0.0.0.0:1234

.fi
.RE

.SH Find out a specific mapping
.PP
.RS

.nf
$ docker container port test 7890/tcp
0.0.0.0:4321

$ docker container port test 7890
0.0.0.0:4321

.fi
.RE

.SH An example showing error for non\-existent mapping
.PP
.RS

.nf
$ docker container port test 7890/udp
2014/06/24 11:53:36 Error: No public port '7890/udp' published for test

.fi
.RE


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for port


.SH SEE ALSO
.PP
\fBdocker\-container(1)\fP
