.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-plugin\-set \- Change settings for a plugin


.SH SYNOPSIS
.PP
\fBdocker plugin set PLUGIN KEY=VALUE [KEY=VALUE...]\fP


.SH DESCRIPTION
.PP
Change settings for a plugin


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for set


.SH SEE ALSO
.PP
\fBdocker\-plugin(1)\fP
