.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-system \- Manage Docker


.SH SYNOPSIS
.PP
\fBdocker system\fP


.SH DESCRIPTION
.PP
Manage Docker


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for system


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-system\-df(1)\fP, \fBdocker\-system\-events(1)\fP, \fBdocker\-system\-info(1)\fP, \fBdocker\-system\-prune(1)\fP
