.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-trust\-signer\-add \- Add a signer


.SH SYNOPSIS
.PP
**docker trust signer add OPTIONS NAME REPOSITORY [REPOSITORY...] **


.SH DESCRIPTION
.PP
Add a signer


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for add

.PP
\fB\-\-key\fP=
    Path to the signer's public key file


.SH SEE ALSO
.PP
\fBdocker\-trust\-signer(1)\fP
