.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-checkpoint\-create \- Create a checkpoint from a running container


.SH SYNOPSIS
.PP
\fBdocker checkpoint create [OPTIONS] CONTAINER CHECKPOINT\fP


.SH DESCRIPTION
.PP
Create a checkpoint from a running container


.SH OPTIONS
.PP
\fB\-\-checkpoint\-dir\fP=""
    Use a custom checkpoint storage directory

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for create

.PP
\fB\-\-leave\-running\fP[=false]
    Leave the container running after checkpoint


.SH SEE ALSO
.PP
\fBdocker\-checkpoint(1)\fP
