.TH "DOCKER" "1" "Aug 2018" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-config\-rm \- Remove one or more configs


.SH SYNOPSIS
.PP
\fBdocker config rm CONFIG [CONFIG...]\fP


.SH DESCRIPTION
.PP
Remove one or more configs


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for rm


.SH SEE ALSO
.PP
\fBdocker\-config(1)\fP
