Name: ZeroMQ
Version: 4.3.3
URL: https://zeromq.org/
Summary: An open-source universal messaging library
Description: ZeroMQ (also known as ØMQ, 0MQ, or zmq) looks like an embeddable
  networking library but acts like a concurrency framework. It gives you sockets
  that carry atomic messages across various transports like in-process,
  inter-process, TCP, and multicast. You can connect sockets N-to-N with
  patterns like fan-out, pub-sub, task distribution, and request-reply. It's
  fast enough to be the fabric for clustered products. Its asynchronous I/O
  model gives you scalable multicore applications, built as asynchronous
  message-processing tasks. It has a score of language APIs and runs on most
  operating systems.