Name: zzz
Version: 0.1.0
URL: https://github.com/jirutka/zzz/
Summary: Suspend or hibernate your computer
Description: A simple program to suspend or hibernate your computer.
  It supports hooks before and after suspending.
