.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-config\-create \- Create a config from a file or STDIN


.SH SYNOPSIS
.PP
\fBdocker config create [OPTIONS] CONFIG file|\-\fP


.SH DESCRIPTION
.PP
Create a config from a file or STDIN


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for create

.PP
\fB\-l\fP, \fB\-\-label\fP=
    Config labels

.PP
\fB\-\-template\-driver\fP=""
    Template driver


.SH SEE ALSO
.PP
\fBdocker\-config(1)\fP
