.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-trust \- Manage trust on Docker images


.SH SYNOPSIS
.PP
\fBdocker trust\fP


.SH DESCRIPTION
.PP
Manage trust on Docker images


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for trust


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-trust\-inspect(1)\fP, \fBdocker\-trust\-key(1)\fP, \fBdocker\-trust\-revoke(1)\fP, \fBdocker\-trust\-sign(1)\fP, \fBdocker\-trust\-signer(1)\fP
