.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-image \- Manage images


.SH SYNOPSIS
.PP
\fBdocker image\fP


.SH DESCRIPTION
.PP
Manage images


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for image


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-image\-build(1)\fP, \fBdocker\-image\-history(1)\fP, \fBdocker\-image\-import(1)\fP, \fBdocker\-image\-inspect(1)\fP, \fBdocker\-image\-load(1)\fP, \fBdocker\-image\-ls(1)\fP, \fBdocker\-image\-prune(1)\fP, \fBdocker\-image\-pull(1)\fP, \fBdocker\-image\-push(1)\fP, \fBdocker\-image\-rm(1)\fP, \fBdocker\-image\-save(1)\fP, \fBdocker\-image\-tag(1)\fP
