.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-volume \- Manage volumes


.SH SYNOPSIS
.PP
\fBdocker volume COMMAND\fP


.SH DESCRIPTION
.PP
The \fB\fCdocker volume\fR command has subcommands for managing data volumes. A data
volume is a specially\-designated directory that by\-passes storage driver
management.

.PP
Data volumes persist data independent of a container's life cycle. When you
delete a container, the Docker daemon does not delete any data volumes. You can
share volumes across multiple containers. Moreover, you can share data volumes
with other computing resources in your system.

.PP
To see help for a subcommand, use:

.PP
.RS

.nf
docker volume COMMAND \-\-help

.fi
.RE

.PP
For full details on using docker volume visit Docker's online documentation.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for volume


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-volume\-create(1)\fP, \fBdocker\-volume\-inspect(1)\fP, \fBdocker\-volume\-ls(1)\fP, \fBdocker\-volume\-prune(1)\fP, \fBdocker\-volume\-rm(1)\fP
