.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-manifest \- Manage Docker image manifests and manifest lists


.SH SYNOPSIS
.PP
\fBdocker manifest COMMAND\fP


.SH DESCRIPTION
.PP
The \fBdocker manifest\fP command has subcommands for managing image manifests and
manifest lists. A manifest list allows you to use one name to refer to the same image
built for multiple architectures.

.PP
To see help for a subcommand, use:

.PP
.RS

.nf
docker manifest CMD \-\-help

.fi
.RE

.PP
For full details on using docker manifest lists, see the registry v2 specification.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for manifest


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-manifest\-annotate(1)\fP, \fBdocker\-manifest\-create(1)\fP, \fBdocker\-manifest\-inspect(1)\fP, \fBdocker\-manifest\-push(1)\fP
