.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-manifest\-annotate \- Add additional information to a local image manifest


.SH SYNOPSIS
.PP
\fBdocker manifest annotate [OPTIONS] MANIFEST\_LIST MANIFEST\fP


.SH DESCRIPTION
.PP
Add additional information to a local image manifest


.SH OPTIONS
.PP
\fB\-\-arch\fP=""
    Set architecture

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for annotate

.PP
\fB\-\-os\fP=""
    Set operating system

.PP
\fB\-\-os\-features\fP=[]
    Set operating system feature

.PP
\fB\-\-variant\fP=""
    Set architecture variant


.SH SEE ALSO
.PP
\fBdocker\-manifest(1)\fP
