.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-logout \- Log out from a Docker registry


.SH SYNOPSIS
.PP
\fBdocker logout [SERVER]\fP


.SH DESCRIPTION
.PP
Log out of a Docker Registry located on the specified \fB\fCSERVER\fR\&. You can
specify a URL or a \fB\fChostname\fR for the \fB\fCSERVER\fR value. If you do not specify a
\fB\fCSERVER\fR, the command attempts to log you out of Docker's public registry
located at \fB\fChttps://registry\-1.docker.io/\fR by default.


.SH EXAMPLES
.SH Log out from a registry on your localhost
.PP
.RS

.nf
# docker logout localhost:8080

.fi
.RE


.SH See also
.PP
\fBdocker\-login(1)\fP to log in to a Docker registry server.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for logout


.SH SEE ALSO
.PP
\fBdocker(1)\fP
