.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-volume\-ls \- List volumes


.SH SYNOPSIS
.PP
\fBdocker volume ls [OPTIONS]\fP


.SH DESCRIPTION
.PP
Lists all the volumes Docker manages. You can filter using the \fB\fC\-f\fR or
\fB\fC\-\-filter\fR flag. The filtering format is a \fB\fCkey=value\fR pair. To specify
more than one filter,  pass multiple flags (for example,
\fB\fC\-\-filter "foo=bar" \-\-filter "bif=baz"\fR)

.PP
The currently supported filters are:

.RS
.IP \(bu 2
\fB\fCdangling\fR (boolean \- \fB\fCtrue\fR or \fB\fCfalse\fR, \fB\fC1\fR or \fB\fC0\fR)
.IP \(bu 2
\fB\fCdriver\fR (a volume driver's name)
.IP \(bu 2
\fB\fClabel\fR (\fB\fClabel=<key>\fR or \fB\fClabel=<key>=<value>\fR)
.IP \(bu 2
\fB\fCname\fR (a volume's name)

.RE


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filter\fP=
    Provide filter values (e.g. 'dangling=true')

.PP
\fB\-\-format\fP=""
    Pretty\-print volumes using a Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for ls

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only display volume names


.SH SEE ALSO
.PP
\fBdocker\-volume(1)\fP
