.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-tag \- Create a tag TARGET\_IMAGE that refers to SOURCE\_IMAGE


.SH SYNOPSIS
.PP
\fBdocker tag SOURCE\_IMAGE[:TAG] TARGET\_IMAGE[:TAG]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker image tag\fR\&.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for tag


.SH SEE ALSO
.PP
\fBdocker(1)\fP
