.TH "DOCKER" "1" " Docker User Manuals" "William Henry" "APRIL 2014" 
.nh
.ad l


.SH NAME
.PP
docker \- Docker image and container command line interface


.SH SYNOPSIS
.PP
\fBdocker\fP [OPTIONS] COMMAND [ARG...]

.PP
\fBdocker\fP [\-\-help|\-v|\-\-version]


.SH DESCRIPTION
.PP
\fBdocker\fP is a client for interacting with the daemon (see \fBdockerd(8)\fP) through the CLI.

.PP
The Docker CLI has over 30 commands. The commands are listed below and each has
its own man page which explain usage and arguments.

.PP
To see the man page for a command run \fBman docker <command>\fP\&.


.SH OPTIONS
.PP
\fB\-\-help\fP
  Print usage statement

.PP
\fB\-\-config\fP=""
  Specifies the location of the Docker client configuration files. The default is '\~/.docker'.

.PP
\fB\-D\fP, \fB\-\-debug\fP=\fItrue\fP|\fIfalse\fP
  Enable debug mode. Default is false.

.PP
\fB\-H\fP, \fB\-\-host\fP=[\fIunix:///var/run/docker.sock\fP]: tcp://[host]:[port][path] to bind or
unix://[/path/to/socket] to use.
  The socket(s) to bind to in daemon mode specified using one or more
  tcp://host:port/path, unix:///path/to/socket, fd://* or fd://socketfd.
  If the tcp port is not specified, then it will default to either \fB\fC2375\fR when
  \fB\fC\-\-tls\fR is off, or \fB\fC2376\fR when \fB\fC\-\-tls\fR is on, or \fB\fC\-\-tlsverify\fR is specified.

.PP
\fB\-l\fP, \fB\-\-log\-level\fP="\fIdebug\fP|\fIinfo\fP|\fIwarn\fP|\fIerror\fP|\fIfatal\fP"
  Set the logging level. Default is \fB\fCinfo\fR\&.

.PP
\fB\-\-tls\fP=\fItrue\fP|\fIfalse\fP
  Use TLS; implied by \-\-tlsverify. Default is false.

.PP
\fB\-\-tlscacert\fP=\fI\~/.docker/ca.pem\fP
  Trust certs signed only by this CA.

.PP
\fB\-\-tlscert\fP=\fI\~/.docker/cert.pem\fP
  Path to TLS certificate file.

.PP
\fB\-\-tlskey\fP=\fI\~/.docker/key.pem\fP
  Path to TLS key file.

.PP
\fB\-\-tlsverify\fP=\fItrue\fP|\fIfalse\fP
  Use TLS and verify the remote (daemon: verify client, client: verify daemon).
  Default is false.

.PP
\fB\-v\fP, \fB\-\-version\fP=\fItrue\fP|\fIfalse\fP
  Print version information and quit. Default is false.


.SH COMMANDS
.PP
Use "docker help" or "docker \-\-help" to get an overview of available commands.


.SH EXAMPLES
.PP
For specific client examples please see the man page for the specific Docker
command. For example:

.PP
.RS

.nf
man docker\-run

.fi
.RE


.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com) based on docker.com source material and internal work.
