.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-attach \- Attach local standard input, output, and error streams to a running container


.SH SYNOPSIS
.PP
\fBdocker attach [OPTIONS] CONTAINER\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container attach\fR\&.


.SH OPTIONS
.PP
\fB\-\-detach\-keys\fP=""
    Override the key sequence for detaching a container

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for attach

.PP
\fB\-\-no\-stdin\fP[=false]
    Do not attach STDIN

.PP
\fB\-\-sig\-proxy\fP[=true]
    Proxy all received signals to the process


.SH SEE ALSO
.PP
\fBdocker(1)\fP
