.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container\-stop \- Stop one or more running containers


.SH SYNOPSIS
.PP
\fBdocker container stop [OPTIONS] CONTAINER [CONTAINER...]\fP


.SH DESCRIPTION
.PP
Stop a container (Send SIGTERM, and then SIGKILL after grace period)


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for stop

.PP
\fB\-t\fP, \fB\-\-time\fP=10
    Seconds to wait for stop before killing it


.SH SEE ALSO
.PP
\fBdocker\-container(1)\fP
