.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-secret\-inspect \- Display detailed information on one or more secrets


.SH SYNOPSIS
.PP
\fBdocker secret inspect [OPTIONS] SECRET [SECRET...]\fP


.SH DESCRIPTION
.PP
Display detailed information on one or more secrets


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-format\fP=""
    Format the output using the given Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for inspect

.PP
\fB\-\-pretty\fP[=false]
    Print the information in a human friendly format


.SH SEE ALSO
.PP
\fBdocker\-secret(1)\fP
