.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-network\-prune \- Remove all unused networks


.SH SYNOPSIS
.PP
\fBdocker network prune [OPTIONS]\fP


.SH DESCRIPTION
.PP
Remove all unused networks


.SH OPTIONS
.PP
\fB\-\-filter\fP=
    Provide filter values (e.g. 'until=<timestamp>\&')

.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Do not prompt for confirmation

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for prune


.SH SEE ALSO
.PP
\fBdocker\-network(1)\fP
