.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-ps \- List containers


.SH SYNOPSIS
.PP
\fBdocker ps [OPTIONS]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container ls\fR\&.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
    Show all containers (default shows just running)

.PP
\fB\-f\fP, \fB\-\-filter\fP=
    Filter output based on conditions provided

.PP
\fB\-\-format\fP=""
    Pretty\-print containers using a Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for ps

.PP
\fB\-n\fP, \fB\-\-last\fP=\-1
    Show n last created containers (includes all states)

.PP
\fB\-l\fP, \fB\-\-latest\fP[=false]
    Show the latest created container (includes all states)

.PP
\fB\-\-no\-trunc\fP[=false]
    Don't truncate output

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only display numeric IDs

.PP
\fB\-s\fP, \fB\-\-size\fP[=false]
    Display total file sizes


.SH SEE ALSO
.PP
\fBdocker(1)\fP
