.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-manifest\-inspect \- Display an image manifest, or manifest list


.SH SYNOPSIS
.PP
\fBdocker manifest inspect [OPTIONS] [MANIFEST\_LIST] MANIFEST\fP


.SH DESCRIPTION
.PP
Display an image manifest, or manifest list


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for inspect

.PP
\fB\-\-insecure\fP[=false]
    Allow communication with an insecure registry

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
    Output additional info including layers and platform


.SH SEE ALSO
.PP
\fBdocker\-manifest(1)\fP
