.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-container\-top \- Display the running processes of a container


.SH SYNOPSIS
.PP
\fBdocker container top CONTAINER [ps OPTIONS]\fP


.SH DESCRIPTION
.PP
Display the running process of the container. ps\-OPTION can be any of the options you would pass to a Linux ps command.

.PP
All displayed information is from host's point of view.


.SH EXAMPLES
.PP
Run \fBdocker container top\fP with the ps option of \-x:

.PP
.RS

.nf
$ docker container top 8601afda2b \-x
PID      TTY       STAT       TIME         COMMAND
16623    ?         Ss         0:00         sleep 99999

.fi
.RE


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for top


.SH SEE ALSO
.PP
\fBdocker\-container(1)\fP
