.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-plugin\-disable \- Disable a plugin


.SH SYNOPSIS
.PP
\fBdocker plugin disable [OPTIONS] PLUGIN\fP


.SH DESCRIPTION
.PP
Disable a plugin


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Force the disable of an active plugin

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for disable


.SH SEE ALSO
.PP
\fBdocker\-plugin(1)\fP
