.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-context\-import \- Import a context from a tar or zip file


.SH SYNOPSIS
.PP
\fBdocker context import CONTEXT FILE|\-\fP


.SH DESCRIPTION
.PP
Import a context from a tar or zip file


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for import


.SH SEE ALSO
.PP
\fBdocker\-context(1)\fP
