.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-config \- Manage Docker configs


.SH SYNOPSIS
.PP
\fBdocker config\fP


.SH DESCRIPTION
.PP
Manage Docker configs


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for config


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-config\-create(1)\fP, \fBdocker\-config\-inspect(1)\fP, \fBdocker\-config\-ls(1)\fP, \fBdocker\-config\-rm(1)\fP
