.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-port \- List port mappings or a specific mapping for the container


.SH SYNOPSIS
.PP
\fBdocker port CONTAINER [PRIVATE\_PORT[/PROTO]]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container port\fR\&.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for port


.SH SEE ALSO
.PP
\fBdocker(1)\fP
