.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-context\-rm \- Remove one or more contexts


.SH SYNOPSIS
.PP
\fBdocker context rm CONTEXT [CONTEXT...]\fP


.SH DESCRIPTION
.PP
Remove one or more contexts


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Force the removal of a context in use

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for rm


.SH SEE ALSO
.PP
\fBdocker\-context(1)\fP
