.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-diff \- Inspect changes to files or directories on a container's filesystem


.SH SYNOPSIS
.PP
\fBdocker diff CONTAINER\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container diff\fR\&.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for diff


.SH SEE ALSO
.PP
\fBdocker(1)\fP
