.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-volume\-inspect \- Display detailed information on one or more volumes


.SH SYNOPSIS
.PP
\fBdocker volume inspect [OPTIONS] VOLUME [VOLUME...]\fP


.SH DESCRIPTION
.PP
Returns information about one or more volumes. By default, this command renders
all results in a JSON array. You can specify an alternate format to execute a
given template is executed for each result. Go's 
\[la]https://golang.org/pkg/text/template/\[ra]
package describes all the details of the format.


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-format\fP=""
    Format the output using the given Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for inspect


.SH SEE ALSO
.PP
\fBdocker\-volume(1)\fP
