.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-secret\-ls \- List secrets


.SH SYNOPSIS
.PP
\fBdocker secret ls [OPTIONS]\fP


.SH DESCRIPTION
.PP
List secrets


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filter\fP=
    Filter output based on conditions provided

.PP
\fB\-\-format\fP=""
    Pretty\-print secrets using a Go template

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for ls

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
    Only display IDs


.SH SEE ALSO
.PP
\fBdocker\-secret(1)\fP
