.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-commit \- Create a new image from a container's changes


.SH SYNOPSIS
.PP
\fBdocker commit [OPTIONS] CONTAINER [REPOSITORY[:TAG]]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker container commit\fR\&.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-author\fP=""
    Author (e.g., "John Hannibal Smith 
\[la]hannibal@a-team.com\[ra]")

.PP
\fB\-c\fP, \fB\-\-change\fP=
    Apply Dockerfile instruction to the created image

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for commit

.PP
\fB\-m\fP, \fB\-\-message\fP=""
    Commit message

.PP
\fB\-p\fP, \fB\-\-pause\fP[=true]
    Pause container during commit


.SH SEE ALSO
.PP
\fBdocker(1)\fP
