.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-rmi \- Remove one or more images


.SH SYNOPSIS
.PP
\fBdocker rmi [OPTIONS] IMAGE [IMAGE...]\fP


.SH DESCRIPTION
.PP
Alias for \fB\fCdocker image rm\fR\&.


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    Force removal of the image

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for rmi

.PP
\fB\-\-no\-prune\fP[=false]
    Do not delete untagged parents


.SH SEE ALSO
.PP
\fBdocker(1)\fP
