.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-plugin \- Manage plugins


.SH SYNOPSIS
.PP
\fBdocker plugin\fP


.SH DESCRIPTION
.PP
Manage plugins


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for plugin


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-plugin\-create(1)\fP, \fBdocker\-plugin\-disable(1)\fP, \fBdocker\-plugin\-enable(1)\fP, \fBdocker\-plugin\-inspect(1)\fP, \fBdocker\-plugin\-install(1)\fP, \fBdocker\-plugin\-ls(1)\fP, \fBdocker\-plugin\-push(1)\fP, \fBdocker\-plugin\-rm(1)\fP, \fBdocker\-plugin\-set(1)\fP, \fBdocker\-plugin\-upgrade(1)\fP
