.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-context \- Manage contexts


.SH SYNOPSIS
.PP
\fBdocker context\fP


.SH DESCRIPTION
.PP
Manage contexts


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for context


.SH SEE ALSO
.PP
\fBdocker(1)\fP, \fBdocker\-context\-create(1)\fP, \fBdocker\-context\-export(1)\fP, \fBdocker\-context\-import(1)\fP, \fBdocker\-context\-inspect(1)\fP, \fBdocker\-context\-ls(1)\fP, \fBdocker\-context\-rm(1)\fP, \fBdocker\-context\-update(1)\fP, \fBdocker\-context\-use(1)\fP
