.TH "DOCKER" "1" "May 2020" "Docker Community" "" 
.nh
.ad l


.SH NAME
.PP
docker\-trust\-key\-generate \- Generate and load a signing key\-pair


.SH SYNOPSIS
.PP
\fBdocker trust key generate NAME\fP


.SH DESCRIPTION
.PP
Generate and load a signing key\-pair


.SH OPTIONS
.PP
\fB\-\-dir\fP=""
    Directory to generate key in, defaults to current directory

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for generate


.SH SEE ALSO
.PP
\fBdocker\-trust\-key(1)\fP
