Name: OpenRC
Version: 0.39
URL: https://wiki.gentoo.org/wiki/Project:OpenRC
Summary: OpenRC is a dependency-based init system
Description: OpenRC is a dependency-based init system that works with the system-provided init program, normally
  /sbin/init. Currently, it does not have an init program of its own.