'\" t
.\"     Title: \fBnixos-enter\fR
  
.\"    Author: Eelco Dolstra
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 01/01/1980
.\"    Manual: NixOS Reference Pages
.\"    Source: NixOS
.\"  Language: English
.\"
.TH "\FBNIXOS\-ENTER\FR" "8" "01/01/1980" "NixOS" "NixOS Reference Pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" enable line breaks after slashes
.cflags 4 /
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nixos-enter \- run a command in a NixOS chroot environment
.SH "SYNOPSIS"
.HP \w'\fBnixos\-enter\fR\ 'u
\fBnixos\-enter\fR [\fB\-\-root\fR\ \fIroot\fR] [\fB\-\-system\fR\ \fIsystem\fR] [\fB\-c\fR\ \fIshell\-command\fR] [\fB\-\-silent\fR] [\fB\-\-help\fR] [\fB\-\-\fR\ \fIarguments\fR]
.SH "DESCRIPTION"
.PP
This command runs a command in a NixOS chroot environment, that is, in a filesystem hierarchy previously prepared using
\fBnixos\-install\fR\&.
.SH "OPTIONS"
.PP
This command accepts the following options:
.PP
\fB\-\-root\fR
.RS 4
The path to the NixOS system you want to enter\&. It defaults to
/mnt\&.
.RE
.PP
\fB\-\-system\fR
.RS 4
The NixOS system configuration to use\&. It defaults to
/nix/var/nix/profiles/system\&. You can enter a previous NixOS configuration by specifying a path such as
/nix/var/nix/profiles/system\-106\-link\&.
.RE
.PP
\fB\-\-command\fR, \fB\-c\fR
.RS 4
The bash command to execute\&.
.RE
.PP
\fB\-\-silent\fR
.RS 4
Suppresses all output from the activation script of the target system\&.
.RE
.PP
\fB\-\-\fR
.RS 4
Interpret the remaining arguments as the program name and arguments to be invoked\&. The program is not executed in a shell\&.
.RE
.SH "EXAMPLES"
.PP
Start an interactive shell in the NixOS installation in
/mnt:
.sp
.if n \{\
.RS 4
.\}
.nf
# nixos\-enter \-\-root /mnt
.fi
.if n \{\
.RE
.\}
.PP
Run a shell command:
.sp
.if n \{\
.RS 4
.\}
.nf
# nixos\-enter \-c \*(Aqls \-l /; cat /proc/mounts\*(Aq
.fi
.if n \{\
.RE
.\}
.PP
Run a non\-shell command:
.sp
.if n \{\
.RS 4
.\}
.nf
# nixos\-enter \-\- cat /proc/mounts
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.PP
\fBEelco Dolstra\fR
.RS 4
Author
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2007-2020 Eelco Dolstra
.br
