'\" t
.\"     Title: \fBnixos-install\fR
  
.\"    Author: Eelco Dolstra
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 01/01/1980
.\"    Manual: NixOS Reference Pages
.\"    Source: NixOS
.\"  Language: English
.\"
.TH "\FBNIXOS\-INSTALL\FR" "8" "01/01/1980" "NixOS" "NixOS Reference Pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" enable line breaks after slashes
.cflags 4 /
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nixos-install \- install bootloader and NixOS
.SH "SYNOPSIS"
.HP \w'\fBnixos\-install\fR\ 'u
\fBnixos\-install\fR [{\ \fB\-\-verbose\fR\ |\ \fB\-v\fR\ }] [\fB\-I\fR\ \fIpath\fR] [\fB\-\-root\fR\ \fIroot\fR] [\fB\-\-system\fR\ \fIpath\fR] [\fB\-\-flake\fR\ \fIflake\-uri\fR] [{\fB\-\-impure\fR}] [\fB\-\-channel\fR\ \fIchannel\fR] [\fB\-\-no\-channel\-copy\fR] [{\ \fB\-\-no\-root\-password\fR\ |\ \fB\-\-no\-root\-passwd\fR\ }] [\fB\-\-no\-bootloader\fR] [{\ \fB\-\-max\-jobs\fR\ |\ \fB\-j\fR\ }\ \fInumber\fR] [\fB\-\-cores\fR\ \fInumber\fR] [\fB\-\-option\fR\ \fIname\fR\ \fIvalue\fR] [\fB\-\-show\-trace\fR] [\fB\-\-keep\-going\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
This command installs NixOS in the file system mounted on
/mnt, based on the NixOS configuration specified in
/mnt/etc/nixos/configuration\&.nix\&. It performs the following steps:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
It copies Nix and its dependencies to
/mnt/nix/store\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
It runs Nix in
/mnt
to build the NixOS configuration specified in
/mnt/etc/nixos/configuration\&.nix\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
It installs the current channel
\(lqnixos\(rq
in the target channel profile (unless
\fB\-\-no\-channel\-copy\fR
is specified)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
It installs the GRUB boot loader on the device specified in the option
\fBboot\&.loader\&.grub\&.device\fR
(unless
\fB\-\-no\-bootloader\fR
is specified), and generates a GRUB configuration file that boots into the NixOS configuration just installed\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
It prompts you for a password for the root account (unless
\fB\-\-no\-root\-password\fR
is specified)\&.
.RE
.PP
This command is idempotent: if it is interrupted or fails due to a temporary problem (e\&.g\&. a network issue), you can safely re\-run it\&.
.SH "OPTIONS"
.PP
This command accepts the following options:
.PP
\fB\-\-verbose\fR / \fB\-v\fR
.RS 4
Increases the level of verbosity of diagnostic messages printed on standard error\&. For each Nix operation, the information printed on standard output is well\-defined; any diagnostic information is printed on standard error, never on standard output\&.
.sp
Please note that this option may be specified repeatedly\&.
.RE
.PP
\fB\-\-root\fR
.RS 4
Defaults to
/mnt\&. If this option is given, treat the directory
\fIroot\fR
as the root of the NixOS installation\&.
.RE
.PP
\fB\-\-system\fR
.RS 4
If this option is provided,
\fBnixos\-install\fR
will install the specified closure rather than attempt to build one from
/mnt/etc/nixos/configuration\&.nix\&.
.sp
The closure must be an appropriately configured NixOS system, with boot loader and partition configuration that fits the target host\&. Such a closure is typically obtained with a command such as
\fBnix\-build \-I nixos\-config=\&./configuration\&.nix \*(Aq<nixpkgs/nixos>\*(Aq \-A system \-\-no\-out\-link\fR
.RE
.PP
\fB\-\-flake\fR \fIflake\-uri\fR#\fIname\fR
.RS 4
Build the NixOS system from the specified flake\&. The flake must contain an output named
nixosConfigurations\&.\fIname\fR\&.
.RE
.PP
\fB\-\-channel\fR
.RS 4
If this option is provided, do not copy the current
\(lqnixos\(rq
channel to the target host\&. Instead, use the specified derivation\&.
.RE
.PP
\fB\-I\fR
.RS 4
Add a path to the Nix expression search path\&. This option may be given multiple times\&. See the NIX_PATH environment variable for information on the semantics of the Nix search path\&. Paths added through
\fI\-I\fR
take precedence over NIX_PATH\&.
.RE
.PP
\fB\-\-max\-jobs\fR, \fB\-j\fR
.RS 4
Sets the maximum number of build jobs that Nix will perform in parallel to the specified number\&. The default is
1\&. A higher value is useful on SMP systems or to exploit I/O latency\&.
.RE
.PP
\fB\-\-cores\fR
.RS 4
Sets the value of the
\fBNIX_BUILD_CORES\fR
environment variable in the invocation of builders\&. Builders can use this variable at their discretion to control the maximum amount of parallelism\&. For instance, in Nixpkgs, if the derivation attribute
\fIenableParallelBuilding\fR
is set to
true, the builder passes the
\fB\-j\fR\fB\fIN\fR\fR
flag to GNU Make\&. The value
0
means that the builder should use all available CPU cores in the system\&.
.RE
.PP
\fB\-\-option\fR \fIname\fR \fIvalue\fR
.RS 4
Set the Nix configuration option
\fIname\fR
to
\fIvalue\fR\&.
.RE
.PP
\fB\-\-show\-trace\fR
.RS 4
Causes Nix to print out a stack trace in case of Nix expression evaluation errors\&.
.RE
.PP
\fB\-\-keep\-going\fR
.RS 4
Causes Nix to continue building derivations as far as possible in the face of failed builds\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Synonym for
\fBman nixos\-install\fR\&.
.RE
.SH "EXAMPLES"
.PP
A typical NixOS installation is done by creating and mounting a file system on
/mnt, generating a NixOS configuration in
/mnt/etc/nixos/configuration\&.nix, and running
\fBnixos\-install\fR\&. For instance, if we want to install NixOS on an
ext4
file system created in
/dev/sda1:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkfs\&.ext4 /dev/sda1
$ mount /dev/sda1 /mnt
$ nixos\-generate\-config \-\-root /mnt
$ # edit /mnt/etc/nixos/configuration\&.nix
$ nixos\-install
$ reboot
.fi
.if n \{\
.RE
.\}
.sp
.SH "AUTHOR"
.PP
\fBEelco Dolstra\fR
.RS 4
Author
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2007-2020 Eelco Dolstra
.br
