Name: google-chrome
Version: 84
URL: https://www.google.com/chrome/
Summary: the web browser from Google
Description: Google Chrome is a cross-platform web browser developed by Google.
  It was first released in 2008 for Microsoft Windows, and was later ported to
  Linux, macOS, iOS, and Android where it is the default browser built into the
  OS.